# Generated by Django 3.1.3 on 2020-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('1', 'Visual Arts'), ('2', 'Crafts'), ('3', 'Photography')], default='Crafts', max_length=50),
            preserve_default=False,
        ),
    ]
