# Generated by Django 3.1.3 on 2020-11-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
