# Generated by Django 3.1.3 on 2020-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201107_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Visual Arts'), ('2', 'Crafts'), ('3', 'Photography'), ('4', 'Sculpture')], max_length=50),
        ),
    ]
