# Generated by Django 3.1.3 on 2020-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201107_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Visual Arts', 'Visual Arts'), ('Crafts', 'Crafts'), ('Photography', 'Photography'), ('Sculpture', 'Sculpture')], max_length=50),
        ),
    ]
